# Book settings
title: 动手学深度学习（Programming Differential Privacy）
author: Joseph P. Near and Chiké Abuah，刘巍然（译）
copyright: "2021"
logo: notebooks/logo.png

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

bibtex_bibfiles:
    - references.bib

repository:
  url: https://github.com/uvm-plaid/programming-dp
  branch: master

sphinx:
  config:
    language: zh_CN